//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slide_5_bai_1a
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int Id { get; set; }
        public string NameStd { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
    }
}
