//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asm
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE
    {
        public int ID { get; set; }
        public string MASV { get; set; }
        public Nullable<double> Tienganh { get; set; }
        public Nullable<double> Tinhoc { get; set; }
        public Nullable<double> GDTC { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
